version: '3.7'

services:
  elasticsearch8:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    container_name: elasticsearch8
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9201:9200"  # redireciona porta externa 9201 → interna 9200
    networks:
      - elasticnet

networks:
  elasticnet:
    driver: bridge
